FROM python:3.9-alpine

RUN apk add --no-cache gcc musl-dev linux-headers && \
    pip install flask && \
    apk del gcc musl-dev linux-headers


WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "backend.py"]


